apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mysql-with-ssl
  annotations:
    description: "mysql-with-ssl"
    iconClass: "icon-jboss"
    tags: "mysql"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: mysql-ssl

- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: mysql-ssl
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: mysql-ssl:latest
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/zotovsa/mysql-ssl-2.git
      type: Git
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: mysql
  spec:
    replicas: 1
    selector:
      deploymentconfig: mysql
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: keycloak
          - name: MYSQL_PASSWORD
            value: keycloak
          - name:  MYSQL_DATABASE
            value: keycloak 
          - name: MYSQL_ROOT_PASSWORD
            value: root 
          image: mysql-ssl:latest
          imagePullPolicy: Always
          name: mysql
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql-ssl:latest
      type: ImageChange
  status: {}

- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mysql
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deploymentconfig: mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

